# Generated by Django 2.0.6 on 2018-06-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='block_users',
            field=models.ManyToManyField(blank=True, related_name='block_friends', to='members.InstagramUser'),
        ),
        migrations.AlterField(
            model_name='instagramuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='my_friends', to='members.InstagramUser'),
        ),
    ]
